import { prisma } from "./prisma";

export interface BlackBeerProductInput {
  sku: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  comparePrice?: number | null; // Usado para almacenar el precio de la promoción "2x"
  stock?: number;
  isFeatured: boolean;
  categorySlug: string;
  imageUrl: string;
}

const BLACKBEER_SEED_PRODUCTS: BlackBeerProductInput[] = [
  // ═══ BURGERS (Vienen con papas) ═══
  {
    sku: "BB-BURG-BLACK",
    name: "BLACK",
    slug: "burger-black",
    description: "Doble medallón de carne, cheddar, panceta, cebolla caramelizada y barbacoa. ¡Viene con papas!",
    price: 12000,
    comparePrice: 22000,
    stock: 50,
    isFeatured: true,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-CLUB",
    name: "CLUB",
    slug: "burger-club",
    description: "Doble medallón de carne, muzzarella, jamón, queso, tomate, lechuga y huevo. ¡Viene con papas!",
    price: 12000,
    comparePrice: 22000,
    stock: 50,
    isFeatured: false,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-CRISPY",
    name: "CRISPY",
    slug: "burger-crispy",
    description: "Doble medallón de carne, cheddar, panceta, bacon cream y cebolla crispy. ¡Viene con papas!",
    price: 12000,
    comparePrice: 22000,
    stock: 50,
    isFeatured: true,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-CHEESE",
    name: "CHESSEBURGUER",
    slug: "burger-cheese",
    description: "Doble medallón de carne, cheddar x 4, ketchup y cebolla brunoise. ¡Viene con papas!",
    price: 12000,
    comparePrice: 22000,
    stock: 50,
    isFeatured: false,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-SIMO",
    name: "SIMO",
    slug: "burger-simo",
    description: "Doble medallón de carne, cheddar, panceta, salsa BB, tomate, lechuga y cebolla brunoise. ¡Viene con papas!",
    price: 12000,
    comparePrice: 22000,
    stock: 50,
    isFeatured: true,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-CHICKEN",
    name: "CHICKEN BLACK",
    slug: "burger-chicken-black",
    description: "Pollo crispy, cheddar, panceta, BBQ, cheddar, lechuga y mayo. ¡Viene con papas!",
    price: 12000,
    comparePrice: 22000,
    stock: 50,
    isFeatured: false,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-MEXA",
    name: "MEXA",
    slug: "burger-mexa",
    description: "Doble medallón de carne, nachos, guacamole y muzzarella. ¡Viene con papas!",
    price: 12000,
    comparePrice: 22000,
    stock: 50,
    isFeatured: false,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1582196016295-f8c8bd4b3a99?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-PATTY",
    name: "PATTY MELT",
    slug: "burger-patty-melt",
    description: "2 medallones de carne + cheddar y cebolla caramelizada o 2 medallones + cheddar + panceta + bacon cream. ¡Con papas!",
    price: 12000,
    comparePrice: 22000,
    stock: 50,
    isFeatured: false,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-VEGGIE",
    name: "VEGGIE",
    slug: "burger-veggie",
    description: "Medallón vegetariano a elección, lechuga, tomate y huevo. ¡Viene con papas!",
    price: 12000,
    comparePrice: 22000,
    stock: 50,
    isFeatured: false,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-BIG",
    name: "BIG BLACK",
    slug: "burger-big-black",
    description: "Cuatro medallones de carne, panceta, cheddar, aros de cebolla y barbacoa. ¡Viene con papas!",
    price: 13500,
    comparePrice: 24000,
    stock: 50,
    isFeatured: true,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-STUNT",
    name: "STUNTBURGUER",
    slug: "burger-stuntburger",
    description: "Triple medallón de carne, cheddar, panceta y mayonesa Heinz. ¡Viene con papas!",
    price: 13500,
    comparePrice: 24000,
    stock: 50,
    isFeatured: false,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-BURG-BRUTA",
    name: "LA BRUTA",
    slug: "burger-la-bruta",
    description: "Cinco medallones de carne, cheddar x 10, panceta y barbacoa. ¡Una bomba que viene con papas!",
    price: 16500,
    comparePrice: null,
    stock: 50,
    isFeatured: true,
    categorySlug: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
  },

  // ═══ LOMOS (Vienen con papas) ═══
  {
    sku: "BB-LOMO-BLACK",
    name: "BLACK",
    slug: "lomo-black",
    description: "Bife de lomo, cheddar, panceta y cebolla caramelizada. ¡Viene con papas!",
    price: 15500,
    comparePrice: 26500,
    stock: 50,
    isFeatured: true,
    categorySlug: "lomos",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-LOMO-CLUB",
    name: "CLUB",
    slug: "lomo-club",
    description: "Bife de lomo, jamón, muzzarella, tomate, lechuga, huevo y mayo casera. ¡Viene con papas!",
    price: 15500,
    comparePrice: 26500,
    stock: 50,
    isFeatured: false,
    categorySlug: "lomos",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-LOMO-MEXA",
    name: "MEXA",
    slug: "lomo-mexa",
    description: "Bife de lomo, guacamole, nachos y muzzarella. ¡Viene con papas!",
    price: 15500,
    comparePrice: 26500,
    stock: 50,
    isFeatured: false,
    categorySlug: "lomos",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
  },

  // ═══ PAPAS ═══
  {
    sku: "BB-PAPA-CLASICA",
    name: "CLASICAS",
    slug: "papa-clasicas",
    description: "Porción de papas fritas tradicionales, crocantes y doradas.",
    price: 6500,
    stock: 100,
    isFeatured: false,
    categorySlug: "papas",
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PAPA-BLACK",
    name: "BLACK",
    slug: "papa-black",
    description: "Papas fritas con abundante cheddar, panceta picada y cebollita de verdeo.",
    price: 7500,
    stock: 100,
    isFeatured: true,
    categorySlug: "papas",
    imageUrl: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PAPA-CLUB",
    name: "CLUB",
    slug: "papa-club",
    description: "Papas fritas gratinadas con muzzarella y revuelto de huevo.",
    price: 7500,
    stock: 100,
    isFeatured: false,
    categorySlug: "papas",
    imageUrl: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PAPA-CONV",
    name: "PAPA CONVERTIDA",
    slug: "papa-convertida",
    description: "Convertí las papas de tu combo en version BLACK o CLUB (1x o 2x en promo).",
    price: 1500,
    comparePrice: 2500,
    stock: 100,
    isFeatured: false,
    categorySlug: "papas",
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PAPA-PELA",
    name: "PAPA PELA",
    slug: "papa-pela",
    description: "Papas fritas cargadas con muzzarella, medallón de carne desmenuzado, panceta y huevo frito.",
    price: 10000,
    stock: 100,
    isFeatured: true,
    categorySlug: "papas",
    imageUrl: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
  },

  // ═══ PIZZAS ═══
  {
    sku: "BB-PIZZA-MUZA",
    name: "MUZARELLA",
    slug: "pizza-muzarella",
    description: "Salsa de tomate, muzzarella fundida y aceitunas.",
    price: 10000,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-DMUZA",
    name: "DOBLE MUZARELLA",
    slug: "pizza-doble-muzarella",
    description: "Salsa de tomate, doble porción de muzzarella derretida y aceitunas.",
    price: 12500,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-FUGA",
    name: "FUGAZZA",
    slug: "pizza-fugazza",
    description: "Muzzarella, cebolla al horno en pluma y aceitunas.",
    price: 12000,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-NAPO",
    name: "NAPOLITANA",
    slug: "pizza-napolitana",
    description: "Muzzarella, rodajas de tomate fresco, ajo, perejil y aceitunas.",
    price: 12000,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-ESPECIAL",
    name: "ESPECIAL",
    slug: "pizza-especial",
    description: "Muzzarella, jamón cocido y aceitunas verdes.",
    price: 12000,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-ESPMOR",
    name: "ESPECIAL CON MORRON",
    slug: "pizza-especial-morron",
    description: "Muzzarella, jamón cocido, morrones asados en tiras y aceitunas.",
    price: 12500,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-ESPHUE",
    name: "ESPECIAL CON MORRON Y HUEVO",
    slug: "pizza-especial-morron-huevo",
    description: "Muzzarella, jamón cocido, morrones asados, huevo duro rallado y aceitunas.",
    price: 13000,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-MUZMOR",
    name: "MUZARELLA CON MORRONES",
    slug: "pizza-muzarella-morrones",
    description: "Muzzarella, aceitunas y morrones asados.",
    price: 11000,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-PEPE",
    name: "PEPERONI",
    slug: "pizza-peperoni",
    description: "Muzzarella y abundantes rodajas de salame peperoni picante.",
    price: 14000,
    stock: 40,
    isFeatured: true,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-PANCE",
    name: "PANCETA",
    slug: "pizza-panceta",
    description: "Muzzarella, panceta ahumada crocante, cebollita de verdeo y aceitunas.",
    price: 14000,
    stock: 40,
    isFeatured: true,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-PALM",
    name: "PALMITOS CON S. GOLF",
    slug: "pizza-palmitos",
    description: "Muzzarella, jamón cocido, palmitos y salsa golf.",
    price: 13000,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-TROP",
    name: "TROPICAL",
    slug: "pizza-tropical",
    description: "Muzzarella, jamón cocido, trozos de ananá y lluvia de azúcar negro caramelizado.",
    price: 13000,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-RUCU",
    name: "RÚCULA",
    slug: "pizza-rucula",
    description: "Muzzarella, jamón crudo, hojas de rúcula fresca y queso parmesano rallado.",
    price: 14000,
    stock: 40,
    isFeatured: true,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-PIZZA-4Q",
    name: "CUATRO QUESOS",
    slug: "pizza-cuatro-quesos",
    description: "Muzzarella, queso sardo, roquefort y provolone fundidos.",
    price: 13000,
    stock: 40,
    isFeatured: false,
    categorySlug: "pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },

  // ═══ EXTRAS ═══
  {
    sku: "BB-EXT-MEDALLON",
    name: "Medallón de carne + cheddar",
    slug: "extra-medallon",
    description: "Agregá un medallón de carne extra con una feta de queso cheddar.",
    price: 2500,
    stock: 200,
    isFeatured: false,
    categorySlug: "extras",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-EXT-CHEDDAR",
    name: "Dip de cheddar",
    slug: "extra-cheddar",
    description: "Salsa de queso cheddar fundido para untar.",
    price: 1500,
    stock: 200,
    isFeatured: false,
    categorySlug: "extras",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-EXT-PALTA",
    name: "Dip de palta",
    slug: "extra-palta",
    description: "Guacamole casero o crema de palta suave.",
    price: 500,
    stock: 200,
    isFeatured: false,
    categorySlug: "extras",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-EXT-BBQ",
    name: "Dip de barbacoa",
    slug: "extra-barbacoa",
    description: "Salsa barbacoa ahumada dulce.",
    price: 1500,
    stock: 200,
    isFeatured: false,
    categorySlug: "extras",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-EXT-MAYO",
    name: "Dip de mayo casera",
    slug: "extra-mayo-casera",
    description: "Mayonesa casera condimentada de la casa.",
    price: 500,
    stock: 200,
    isFeatured: false,
    categorySlug: "extras",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
  },

  // ═══ TRAGOS CLÁSICOS (1x: $7.000 / 2x: $12.000) ═══
  {
    sku: "BB-DRINK-DAIQUIRI",
    name: "Daiquiri",
    slug: "trago-daiquiri",
    description: "Trago clásico refrescante. Sabores: Frutilla, Durazno o Ananá.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-CUBALIBRE",
    name: "Cuba Libre",
    slug: "trago-cuba-libre",
    description: "Ron, Coca-Cola y un toque de limón.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-NEGRONI",
    name: "Negroni",
    slug: "trago-negroni",
    description: "Gin, Campari y Vermouth dulce rosso.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-APEROL",
    name: "Aperol Spritz",
    slug: "trago-aperol-spritz",
    description: "Aperol, espumante, soda y rodaja de naranja fresca.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-CAIPIRINHA",
    name: "Caipirinha",
    slug: "trago-caipirinha",
    description: "Cachaça de primera, lima machacada y azúcar.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-MALIBU",
    name: "Orange Malibu",
    slug: "trago-orange-malibu",
    description: "Ron de coco Malibu y jugo de naranja exprimido.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-CAIPIROSKA",
    name: "Caipiroska",
    slug: "trago-caipiroska",
    description: "Vodka, lima machacada y almíbar/azúcar.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-GREENDAY",
    name: "Green Day",
    slug: "trago-green-day",
    description: "Una mezcla cítrica y refrescante de color verde característico.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-GINTONIC",
    name: "Gin Tónic",
    slug: "trago-gin-tonic",
    description: "Gin nacional seleccionado con agua tónica premium y limón/pepino.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-CYNAR",
    name: "Cynar Julio",
    slug: "trago-cynar-julio",
    description: "Aperitivo Cynar con jugo de pomelo o gaseosa de pomelo.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-FERNET",
    name: "Fernet",
    slug: "trago-fernet",
    description: "Fernet Branca original con Coca-Cola y abundante hielo.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: true,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-CAMPARI",
    name: "Campari",
    slug: "trago-campari",
    description: "Campari con jugo de naranja natural.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-DRINK-MOJITO",
    name: "Mojito",
    slug: "trago-mojito",
    description: "Ron, menta fresca, lima, azúcar y soda. Sabores a elección: Clásico, Malibu Melón o Maracuyá.",
    price: 7000,
    comparePrice: 12000,
    stock: 100,
    isFeatured: true,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },

  // ═══ ESPECIALES 1L (1x: $11.000 / 2x: $18.500) ═══
  {
    sku: "BB-ESP-CAIPIBLUE",
    name: "Caipi Blue 1L",
    slug: "especial-caipi-blue-1l",
    description: "Nuestra Caipirinha especial de la casa de 1 Litro con Blue Curacao.",
    price: 11000,
    comparePrice: 18500,
    stock: 80,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-ESP-SUNSET",
    name: "Sunset 1L",
    slug: "especial-sunset-1l",
    description: "Trago frutal y veraniego Sunset en presentación de 1 Litro.",
    price: 11000,
    comparePrice: 18500,
    stock: 80,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-ESP-LEMONBLACK",
    name: "Lemon Black 1L",
    slug: "especial-lemon-black-1l",
    description: "Especial cítrico de limón con un toque BlackBeer de 1 Litro.",
    price: 11000,
    comparePrice: 18500,
    stock: 80,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-ESP-GINPAFF",
    name: "Gin Paff 1L",
    slug: "especial-gin-paff-1l",
    description: "Un refrescante cóctel de Gin con el toque dulce de Paff de 1 Litro.",
    price: 11000,
    comparePrice: 18500,
    stock: 80,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-ESP-RAINBOW",
    name: "Rainbow 1L",
    slug: "especial-rainbow-1l",
    description: "Trago súper colorido Rainbow con capas de sabores en 1 Litro.",
    price: 11000,
    comparePrice: 18500,
    stock: 80,
    isFeatured: true,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-ESP-GREEN",
    name: "Green 1L",
    slug: "especial-green-1l",
    description: "Refrescante cóctel herbal Green en presentación de 1 Litro.",
    price: 11000,
    comparePrice: 18500,
    stock: 80,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-ESP-VIOLET",
    name: "Violet 1L",
    slug: "especial-violet-1l",
    description: "Especial de color Violet con notas florales y frutales de 1 Litro.",
    price: 11000,
    comparePrice: 18500,
    stock: 80,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-ESP-ORANGE",
    name: "Orange 1L",
    slug: "especial-orange-1l",
    description: "Especial Orange súper cítrico de naranja y licores en 1 Litro.",
    price: 11000,
    comparePrice: 18500,
    stock: 80,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },

  // ═══ TRAGOS DE AUTOR 500ML (1x: $9.000 / 2x: $15.500) ═══
  {
    sku: "BB-AUT-PINK-500",
    name: "Pink 500ml",
    slug: "autor-pink-500ml",
    description: "Vodka Raspberry, granadina y frutos rojos (500ml).",
    price: 9000,
    comparePrice: 15500,
    stock: 70,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-JAGGER-500",
    name: "Mojito Jagger 500ml",
    slug: "autor-mojito-jagger-500ml",
    description: "Jagger, jugo de limón, hojas de menta y soda (500ml).",
    price: 9000,
    comparePrice: 15500,
    stock: 70,
    isFeatured: true,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-BLACK-500",
    name: "Black Autor 500ml",
    slug: "autor-black-500ml",
    description: "Gin, blue curacao y licor de pomelo (500ml).",
    price: 9000,
    comparePrice: 15500,
    stock: 70,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-GUMMY-500",
    name: "Gummy Gin 500ml",
    slug: "autor-gummy-gin-500ml",
    description: "Gin, malibú, tónica y gomitas (500ml).",
    price: 9000,
    comparePrice: 15500,
    stock: 70,
    isFeatured: true,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-BLUE-500",
    name: "Blue Autor 500ml",
    slug: "autor-blue-500ml",
    description: "Vodka, blue curacao y gomitas (500ml).",
    price: 9000,
    comparePrice: 15500,
    stock: 70,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-CAIPIJAG-500",
    name: "Caipi Jagger 500ml",
    slug: "autor-caipi-jagger-500ml",
    description: "Jagger, limón y tónica (500ml).",
    price: 9000,
    comparePrice: 15500,
    stock: 70,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-RED-500",
    name: "Red Autor 500ml",
    slug: "autor-red-500ml",
    description: "Ron dorado, aperol, malibú y pulpa de frutilla (500ml).",
    price: 9000,
    comparePrice: 15500,
    stock: 70,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },

  // ═══ TRAGOS DE AUTOR 1L (1x: $14.000 / 2x: $24.500) ═══
  {
    sku: "BB-AUT-PINK-1L",
    name: "Pink 1L",
    slug: "autor-pink-1l",
    description: "Vodka Raspberry, granadina y frutos rojos (1 Litro).",
    price: 14000,
    comparePrice: 24500,
    stock: 60,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-JAGGER-1L",
    name: "Mojito Jagger 1L",
    slug: "autor-mojito-jagger-1l",
    description: "Jagger, jugo de limón, hojas de menta y soda (1 Litro).",
    price: 14000,
    comparePrice: 24500,
    stock: 60,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-BLACK-1L",
    name: "Black Autor 1L",
    slug: "autor-black-1l",
    description: "Gin, blue curacao y licor de pomelo (1 Litro).",
    price: 14000,
    comparePrice: 24500,
    stock: 60,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-GUMMY-1L",
    name: "Gummy Gin 1L",
    slug: "autor-gummy-gin-1l",
    description: "Gin, malibú, tónica y gomitas (1 Litro).",
    price: 14000,
    comparePrice: 24500,
    stock: 60,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-BLUE-1L",
    name: "Blue Autor 1L",
    slug: "autor-blue-1l",
    description: "Vodka, blue curacao y gomitas (1 Litro).",
    price: 14000,
    comparePrice: 24500,
    stock: 60,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-CAIPIJAG-1L",
    name: "Caipi Jagger 1L",
    slug: "autor-caipi-jagger-1l",
    description: "Jagger, limón y tónica (1 Litro).",
    price: 14000,
    comparePrice: 24500,
    stock: 60,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-AUT-RED-1L",
    name: "Red Autor 1L",
    slug: "autor-red-1l",
    description: "Ron dorado, aperol, malibú y pulpa de frutilla (1 Litro).",
    price: 14000,
    comparePrice: 24500,
    stock: 60,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },

  // ═══ TRAGOS DE LA CASA ($16.000) ═══
  {
    sku: "BB-HOUSE-FRUTILLITA",
    name: "Frutillita",
    slug: "casa-frutillita",
    description: "Trago súper cremoso licuado con frutillas frescas, crema y alcohol.",
    price: 16000,
    stock: 100,
    isFeatured: true,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-HOUSE-BANANITA",
    name: "Bananita",
    slug: "casa-bananita",
    description: "Trago de licuado de banana con el sabor clásico de bananita dolca y alcohol.",
    price: 16000,
    stock: 100,
    isFeatured: false,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
  {
    sku: "BB-HOUSE-BAILEYS",
    name: "Baileys de la Casa",
    slug: "casa-baileys",
    description: "Nuestra exquisita y sedosa receta casera de licor de crema irlandesa.",
    price: 16000,
    stock: 100,
    isFeatured: true,
    categorySlug: "tragos",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
  },
];

/**
 * Verifica si hay productos en la base de datos y la puebla
 * utilizando operaciones upsert idempotentes.
 */
export async function initializeDatabase(force = false) {
  try {
    if (!force) {
      const productCount = await prisma.product.count();
      if (productCount > 0) {
        return;
      }
    }

    console.log("🚀 Inicializando catálogo BlackBeer Mza...");

    // 1. Crear o actualizar categorías
    const categorySlugs = ["burgers", "lomos", "papas", "pizzas", "extras", "tragos"];
    const categoryMap: Record<string, string> = {};

    for (let i = 0; i < categorySlugs.length; i++) {
      const slug = categorySlugs[i];
      const name = slug === "burgers" ? "Burgers" : slug.charAt(0).toUpperCase() + slug.slice(1);
      const cat = await prisma.category.upsert({
        where: { slug },
        update: { name, sortOrder: i },
        create: {
          name,
          slug,
          isActive: true,
          sortOrder: i,
        },
      });
      categoryMap[slug] = cat.id;
    }

    // 2. Crear o actualizar productos
    for (const p of BLACKBEER_SEED_PRODUCTS) {
      const categoryId = categoryMap[p.categorySlug] || null;

      const product = await prisma.product.upsert({
        where: { sku: p.sku },
        update: {
          name: p.name,
          slug: p.slug,
          description: p.description,
          price: p.price,
          comparePrice: p.comparePrice || null,
          isFeatured: p.isFeatured,
          categoryId,
        },
        create: {
          sku: p.sku,
          name: p.name,
          slug: p.slug,
          description: p.description,
          price: p.price,
          comparePrice: p.comparePrice || null,
          isFeatured: p.isFeatured,
          isActive: true,
          categoryId,
        },
      });

      // Asegurar que exista al menos una imagen asociada
      const existingImage = await prisma.productImage.findFirst({
        where: { productId: product.id },
      });

      if (existingImage) {
        await prisma.productImage.update({
          where: { id: existingImage.id },
          data: {
            url: p.imageUrl,
            alt: p.name,
          },
        });
      } else {
        await prisma.productImage.create({
          data: {
            productId: product.id,
            url: p.imageUrl,
            alt: p.name,
            sortOrder: 0,
          },
        });
      }
    }

    console.log("✅ ¡Siembra/Actualización de catálogo de BlackBeer Mza completada con éxito!");
  } catch (error) {
    console.error("⚠️ Error inicializando la base de datos:", error);
  }
}
